# Generated by Django 3.1.5 on 2021-04-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
