# Generated by Django 3.1.5 on 2021-04-07 07:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyStudent',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('school.student',),
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
    ]
